schedule/application/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps import views
from django.urls import include
from django.urls import path

# from django.views.generic import TemplateView
# from login.sitemaps import LoginStaticSitemap

# Sitemaps
sitemaps = {
    #    'login-static': LoginStaticSitemap
}

# URL Patterns
urlpatterns = [
    # robots.txt
    # path('robots.txt', TemplateView.as_view(template_name='random/robots.txt')),

    # sitemap.xml
    path('sitemap.xml', views.index, {'sitemaps': sitemaps}, name='sitemap'),

    # sitemap-<section>-static.xml (for example - sitemap-login-static.xml)
    path('sitemap-<section>.xml', views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

# Static Content
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# i18n URL Patterns
urlpatterns += i18n_patterns(
    # Schedule URLs
    path('', include('roster.urls')),
    path('login/', include('login.urls')),

    # Django Registration / Password URLs
    path('', include('django.contrib.auth.urls'))
)

# Error Pages
# handler400 = Error400.as_view()
# handler403 = Error403.as_view()
# handler404 = Error404.as_view()
# handler500 = Error500.as_view()

# Debug Settings
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

schedule/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('', views.Index.as_view(redirect_authenticated_user=True), name='login'),

    path('create', views.Create.as_view(), name='create'),

    path('logout', LogoutView.as_view(), name='logout'),

    path('password', views.Password.as_view(), name='password'),

    path('<int:pk>/delete', views.Delete.as_view(), name='delete')
]

schedule/roster/urls.py
from django.urls import path

from roster import views

app_name = 'roster'

urlpatterns = [
    path('', views.Search.as_view(), name='search'),

    path('download', views.Download.as_view(), name='download'),

    path('preview', views.PreviewAll.as_view(), name='preview-all'),

    path('<int:pk>/preview', views.PreviewEmployee.as_view(), name='preview-employee'),

    path('<int:pk>/profile', views.Profile.as_view(), name='profile'),

    path('<int:pk>/schedule', views.Schedule.as_view(), name='schedule')
]

schedule/login/models.py
import pytz
from django.conf import settings
from django.contrib.auth import models as auth_models
from django.contrib.auth.hashers import get_random_string
from django.core import validators
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import gettext_lazy as _

TIME_ZONE_CHOICES = (
    sorted([(x, x) for x in pytz.all_timezones_set])
)


class UserManager(auth_models.BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """

        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)

        if password is None:
            password = self.make_random_password()

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        subject = 'User Registration - marina.gwhcp.dev'

        message = "Hey,\n\n"
        message += "Thank you for registering on https://marina.gwhcp.dev:8443\n\n"
        message += "Here are a few details you will need:\n\n"
        message += "Username: %s\n" % email
        message += "Password: %s\n\n" % password
        message += "After logging in, please change your password.\n\n"
        message += "Thank you,\n"
        message += "~ Marina Management"

        email_from = settings.DEFAULT_FROM_EMAIL
        recipient_list = [email]
        send_mail(subject, message, email_from, recipient_list)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Account(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    class Facility(models.TextChoices):
        BGM = 'bgm', _('BGM')
        SCM = 'scm', _('SCM')

    class FormDisplay(models.TextChoices):
        COMPACT = 'compact', _('Compact')
        EXPAND = 'expand', _('Expanded')

    class HelpText(models.IntegerChoices):
        NO = 0, _('No')
        YES = 1, _('Yes')

    class Locale(models.TextChoices):
        DE = 'de', _('German')
        EN = 'en', _('English')

    class TimeFormat(models.TextChoices):
        LAMEN_LONG = 'l, F d, Y g:i:s A', 'Sunday, January 01, 2000 1:00:00 PM'
        LAMEN_MED = 'F d, Y g:i:s A', 'January 01, 2000 1:00:00 PM'
        LAMEN_SHORT = 'Y-m-d g:i:s A', '2000-01-01 1:00:00 PM'
        STANDARD_LONG = 'l, F d, Y H:i:s', 'Sunday, January 01, 2000 13:00:00'
        STANDARD_MED = 'F d, Y H:i:s', 'January 01, 2000 13:00:00'
        STANDARD_SHORT = 'Y-m-d H:i:s', '2000-01-01 13:00:00'

    date_from = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created On')
    )

    email = models.EmailField(
        validators=[
            validators.MinLengthValidator(5),
            validators.EmailValidator
        ],
        verbose_name=_('Email Address'),
        unique=True,
        blank=False,
        null=False,
        help_text=_('Email address for any notifications.')
    )

    facility = models.CharField(
        max_length=3,
        choices=Facility.choices,
        default='scm',
        blank=False,
        null=False,
        verbose_name=_('Facility'),
        help_text=_('Choose a location.')
    )

    first_name = models.CharField(
        max_length=255,
        validators=[
            validators.RegexValidator('^[a-zA-Z .\'-]+$')
        ],
        verbose_name=_('First Name'),
        blank=False,
        null=False,
        help_text=_('Your legal first name.')
    )

    form_display = models.CharField(
        max_length=7,
        choices=FormDisplay.choices,
        default='expand',
        verbose_name=_('Form Display'),
        blank=False,
        null=False,
        help_text=_('Choose how forms should be displayed.')
    )

    help_text = models.IntegerField(
        choices=HelpText.choices,
        default=1,
        verbose_name=_('Help Text'),
        help_text=_('Choose if help text should be displayed.')
    )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    last_name = models.CharField(
        max_length=255,
        validators=[
            validators.RegexValidator('^[a-zA-Z .\'-]+$')
        ],
        verbose_name=_('Last Name'),
        blank=False,
        null=False,
        help_text=_('Your legal last name.')
    )

    locale = models.CharField(
        max_length=2,
        choices=Locale.choices,
        default='en',
        verbose_name=_('Language'),
        blank=False,
        null=False,
        help_text=_('Choose a default language.')
    )

    time_format = models.CharField(
        max_length=255,
        choices=TimeFormat.choices,
        default='Y-m-d H:i:s',
        verbose_name=_('Time Format'),
        blank=False,
        null=False,
        help_text=_('Choose a preferred time format.')
    )

    time_zone = models.CharField(
        max_length=32,
        choices=TIME_ZONE_CHOICES,
        default='UTC',
        verbose_name=_('Time Zone'),
        blank=False,
        null=False,
        help_text=_('Choose a preferred time zone.')
    )

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    objects = UserManager()

    class Meta:
        db_table = 'account'

        permissions = [
            ('change_password', 'Can change password'),
            ('view_password', 'Can view password')
        ]

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def create_account(self):
        extra_fields = {}

        extra_fields.setdefault('first_name', self.first_name)
        extra_fields.setdefault('last_name', self.last_name)
        extra_fields.setdefault('facility', self.facility)

        Account.objects.create_user(email='%s@marina.gwhcp.dev' % get_random_string(), **extra_fields)

schedule/login/forms.py
from django import forms

from login import models


class FormCreate(forms.ModelForm):
    class Meta:
        model = models.Account

        fields = [
            'facility',
            'first_name',
            'last_name'
        ]

    def save(self, commit=True):
        instance = super(FormCreate, self).save(commit=False)

        instance.create_account()

        return instance

schedule/login/views.py
from django.contrib import messages
from django.contrib.admin import forms as admin_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views import generic

from login import forms


class Create(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'login/create.html'

    form_class = forms.FormCreate

    success_url = reverse_lazy('roster:search')

    success_message = _('Employee has been created.')


class Delete(LoginRequiredMixin, generic.DeleteView):
    success_url = reverse_lazy('roster:search')

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()

        if obj.is_superuser:
            messages.add_message(request, messages.INFO, _('Administrator cannot be removed.'))

            return redirect(self.success_url)
        else:
            messages.success(self.request, _('Employee has been removed.'))

            return super(Delete, self).delete(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return get_object_or_404(get_user_model(), pk=self.kwargs['pk'], is_staff=True)


class Index(SuccessMessageMixin, LoginView):
    template_name = 'login/login.html'

    form_class = admin_forms.AuthenticationForm


class Password(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    form_class = PasswordChangeForm

    template_name = 'login/password.html'

    success_url = reverse_lazy('login:password')

    success_message = _('Updated password.')

schedule/login/templates/login/create.html
{% extends 'asset/layout/layout.html' %}

{% block content %}

    <div class="col-lg-4 m-auto p-3">
        {% include 'login/nav.html' %}

        <form action="{% url 'login:create' %}" method="post" novalidate>

            {% csrf_token %}

            <div class="card">
                <div class="card-header">{{ _('New Employee') }}</div>

                <div class="card-body"
                     id="pwd-container">
                    {% include 'form/input.html' with input=form.first_name is_required=True %}
                    {% include 'form/input.html' with input=form.last_name is_required=True %}
                    {% include 'form/select.html' with select=form.facility is_required=True %}
                </div>

                <div class="card-footer bg-transparent border-0">
                    {% include 'form/submit_create.html' %}
                </div>
            </div>

        </form>
    </div>

{% endblock %}

schedule/login/templates/login/login.html
{% extends 'asset/layout/layout.html' %}

{% block content %}

    <div class="col-lg-4 ml-auto mr-auto pt-5">
        <form action="{% url 'login:login' %}" method="post" novalidate>

            {% csrf_token %}

            <input type="hidden" name="next" value="{{ next }}">

            <div class="card mb-3">
                <div class="card-header">{{ _('Login') }}</div>

                <div class="card-body">
                    {% if form.errors %}
                        <div class="border border-danger p-3 mb-3">
                            {{ _("Your email address and password didn't match. Please try again.") }}
                        </div>
                    {% endif %}

                    {% include 'form/input.html' with input=form.username is_required=True %}
                    {% include 'form/password.html' with password=form.password is_required=True %}

                    <div class="card-text">
                        <a href="{% url 'password_reset' %}">{{ _('Forgot password?') }}</a>
                    </div>
                </div>

                <div class="card-footer bg-transparent border-0">
                    {% include 'form/submit_login.html' %}
                </div>
            </div>

        </form>
    </div>

{% endblock %}

schedule/login/templates/login/nav.html
<ul class="nav nav-tabs mb-2">
    <li class="nav-item">
        <a href="{% url 'roster:search' %}"
           class="nav-link text-dark">
            <i class="fas fa-search"></i> {{ _('Search') }}</a>
    </li>

    <li class="nav-item">
        <a href="{% url 'login:create' %}"
           class="nav-link active text-dark">
            <i class="fas fa-plus-circle"></i> {{ _('Create') }}
        </a>
    </li>
</ul>

schedule/login/templates/login/password.html
{% extends 'asset/layout/layout.html' %}

{% block content %}

    <div class="col-lg-4 m-auto p-3">
        <form action="{% url 'login:password' %}" method="post" novalidate>

            {% csrf_token %}

            <div class="card mb-3">
                <div class="card-header">{{ _('Change Password') }}</div>

                <div class="card-body"
                     id="pwd-container">
                    <div class="labelWrapper">
                        <div class="labelHeader">{{ _('Email Address') }}</div>
                        <div>{{ user.email|escape }}</div>
                    </div>

                    {% include 'form/password.html' with password=form.old_password is_required=True %}
                    {% include 'form/password.html' with password=form.new_password1 is_required=True %}
                    {% include 'form/password.html' with password=form.new_password2 is_required=True %}
                </div>

                <div class="card-footer bg-transparent border-0">
                    {% include 'form/submit_update.html' %}
                </div>
            </div>

        </form>
    </div>

{% endblock content %}