schedule/application/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps import views
from django.urls import include
from django.urls import path

# from django.views.generic import TemplateView
# from login.sitemaps import LoginStaticSitemap

# Sitemaps
sitemaps = {
    #    'login-static': LoginStaticSitemap
}

# URL Patterns
urlpatterns = [
    # robots.txt
    # path('robots.txt', TemplateView.as_view(template_name='random/robots.txt')),

    # sitemap.xml
    path('sitemap.xml', views.index, {'sitemaps': sitemaps}, name='sitemap'),

    # sitemap-<section>-static.xml (for example - sitemap-login-static.xml)
    path('sitemap-<section>.xml', views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

# Static Content
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# i18n URL Patterns
urlpatterns += i18n_patterns(
    # Schedule URLs
    path('', include('roster.urls')),
    path('login/', include('login.urls')),

    # Django Registration / Password URLs
    path('', include('django.contrib.auth.urls'))
)

# Error Pages
# handler400 = Error400.as_view()
# handler403 = Error403.as_view()
# handler404 = Error404.as_view()
# handler500 = Error500.as_view()

# Debug Settings
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

schedule/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('', views.Index.as_view(redirect_authenticated_user=True), name='login'),

    path('create', views.Create.as_view(), name='create'),

    path('logout', LogoutView.as_view(), name='logout'),

    path('password', views.Password.as_view(), name='password'),

    path('<int:pk>/delete', views.Delete.as_view(), name='delete')
]

schedule/roster/urls.py
from django.urls import path

from roster import views

app_name = 'roster'

urlpatterns = [
    path('', views.Search.as_view(), name='search'),

    path('download', views.Download.as_view(), name='download'),

    path('preview', views.PreviewAll.as_view(), name='preview-all'),

    path('<int:pk>/preview', views.PreviewEmployee.as_view(), name='preview-employee'),

    path('<int:pk>/profile', views.Profile.as_view(), name='profile'),

    path('<int:pk>/schedule', views.Schedule.as_view(), name='schedule')
]

schedule/asset/templates/asset/layout/layout.html
{% load template_breadcrumb %}

{% load compress %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Schedule{% gwhcp_template_title %}">
    <meta name="author" content="Sammie S. Taunton">

    <title>Schedule{% gwhcp_template_title %}</title>

    <!-- Start Default CSS -->
    {% compress css %}
    <link rel="stylesheet"
          href="{% static 'webpack/vendor-css.css' %}"
          type="text/css">
    {% endcompress %}

    {% compress css %}
    <link rel="stylesheet"
          href="{% static 'asset/css/schedule.css' %}"
          type="text/css">
    {% endcompress %}

    {% compress css %}
    <link rel="stylesheet"
          href="{% static 'asset/css/layout.css' %}"
          type="text/css">
    {% endcompress %}
    <!-- End Default CSS -->

    <!-- Start Secondary CSS -->
    {% block css %}{% endblock %}
    <!-- End Secondary CSS -->
</head>

<body>

<!-- Start Navbar -->
{% include 'asset/layout/nav_top.html' %}
<!-- End Navbar -->

<!-- Start Content Container -->
<div class="container-fluid pt-3">

    <!-- Start Flash Messenger -->
    {% if messages %}
        {% for message in messages %}
        <div class="col-lg-12 alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show d-print-none"
             role="alert">
            <button type="button"
                    class="close"
                    data-dismiss="alert"
                    aria-label="{{ _('Close') }}">

                <span aria-hidden="true">&times;</span>
            </button>

            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    <!-- End Flash Messenger -->

    <!-- Start Content -->{% block content %}{% endblock %}<!-- End Content -->

</div>
<!-- End Content Container -->

<!-- Start Default JS -->
{% compress js %}
<script src="{% static 'webpack/vendor.js' %}"></script>
{% endcompress %}

{% compress js %}
<script src="{% static 'form/js/blockui.js' %}"></script>
{% endcompress %}

{% compress js %}
<script src="{% static 'asset/js/custom.js' %}"></script>
{% endcompress %}
<!-- End Default JS -->

<!-- Start Secondary JS -->
{% block js %}{% endblock %}
<!-- End Secondary JS -->

</body>

</html>

schedule/asset/templates/asset/layout/nav_top.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'roster:search' %}"><i class="far fa-calendar-alt"></i> {{ _('Schedule') }}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavBarTop"
            aria-controls="NavBarTop" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-align-justify"></i>
    </button>

    {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="NavBarTop">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login:password' %}">
                        <i class="fas fa-user-shield"></i> {{ _('Change Password') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login:logout' %}">
                        <i class="fas fa-sign-out-alt fa-fw"></i> {{ _('Logout') }}
                    </a>
                </li>
            </ul>
        </div>
    {% endif %}
</nav>