schedule/application/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps import views
from django.urls import include
from django.urls import path

# from django.views.generic import TemplateView
# from login.sitemaps import LoginStaticSitemap

# Sitemaps
sitemaps = {
    #    'login-static': LoginStaticSitemap
}

# URL Patterns
urlpatterns = [
    # robots.txt
    # path('robots.txt', TemplateView.as_view(template_name='random/robots.txt')),

    # sitemap.xml
    path('sitemap.xml', views.index, {'sitemaps': sitemaps}, name='sitemap'),

    # sitemap-<section>-static.xml (for example - sitemap-login-static.xml)
    path('sitemap-<section>.xml', views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

# Static Content
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# i18n URL Patterns
urlpatterns += i18n_patterns(
    # Schedule URLs
    path('', include('roster.urls')),
    path('login/', include('login.urls')),

    # Django Registration / Password URLs
    path('', include('django.contrib.auth.urls'))
)

# Error Pages
# handler400 = Error400.as_view()
# handler403 = Error403.as_view()
# handler404 = Error404.as_view()
# handler500 = Error500.as_view()

# Debug Settings
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

schedule/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('', views.Index.as_view(redirect_authenticated_user=True), name='login'),

    path('create', views.Create.as_view(), name='create'),

    path('logout', LogoutView.as_view(), name='logout'),

    path('password', views.Password.as_view(), name='password'),

    path('<int:pk>/delete', views.Delete.as_view(), name='delete')
]

schedule/roster/urls.py
from django.urls import path

from roster import views

app_name = 'roster'

urlpatterns = [
    path('', views.Search.as_view(), name='search'),

    path('download', views.Download.as_view(), name='download'),

    path('preview', views.PreviewAll.as_view(), name='preview-all'),

    path('<int:pk>/preview', views.PreviewEmployee.as_view(), name='preview-employee'),

    path('<int:pk>/profile', views.Profile.as_view(), name='profile'),

    path('<int:pk>/schedule', views.Schedule.as_view(), name='schedule')
]

schedule/roster/models.py
from django.conf import settings
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import FieldTracker


class Roster(models.Model):
    account = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='roster_account',
        on_delete=models.CASCADE,
        primary_key=True
    )

    is_sunday = models.BooleanField(
        default=False,
        verbose_name=_('Sunday')
    )

    has_break_sunday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_sunday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_sunday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    is_monday = models.BooleanField(
        default=False,
        verbose_name=_('Monday')
    )

    has_break_monday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_monday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_monday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    is_tuesday = models.BooleanField(
        default=False,
        verbose_name=_('Tuesday')
    )

    has_break_tuesday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_tuesday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_tuesday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    is_wednesday = models.BooleanField(
        default=False,
        verbose_name=_('Wednesday')
    )

    has_break_wednesday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_wednesday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_wednesday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    is_thursday = models.BooleanField(
        default=False,
        verbose_name=_('Thursday')
    )

    has_break_thursday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_thursday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_thursday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    is_friday = models.BooleanField(
        default=False,
        verbose_name=_('Friday')
    )

    has_break_friday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_friday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_friday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    is_saturday = models.BooleanField(
        default=False,
        verbose_name=_('Saturday')
    )

    has_break_saturday = models.BooleanField(
        default=False,
        verbose_name=_('Break')
    )

    start_time_saturday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('Start Time')
    )

    end_time_saturday = models.CharField(
        max_length=4,
        validators=[
            validators.RegexValidator('^[0-9]+$')
        ],
        blank=True,
        null=True,
        verbose_name=_('End Time')
    )

    tracker = FieldTracker()

    class Meta:
        db_table = 'roster'

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)

        error = {}

        is_day = {
            'sunday': self.is_sunday,
            'monday': self.is_monday,
            'tuesday': self.is_tuesday,
            'wednesday': self.is_wednesday,
            'thursday': self.is_thursday,
            'friday': self.is_friday,
            'saturday': self.is_saturday
        }

        validation_error = _('Value must be set.')

        for key, value in is_day.items():
            # Sunday
            if value is True and key == 'sunday':
                if self.start_time_sunday is None:
                    error['start_time_sunday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_sunday is None:
                    error['end_time_sunday'] = ValidationError(validation_error, code='invalid')

            # Monday
            if value is True and key == 'monday':
                if self.start_time_monday is None:
                    error['start_time_monday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_monday is None:
                    error['end_time_monday'] = ValidationError(validation_error, code='invalid')

            # Tuesday
            if value is True and key == 'tuesday':
                if self.start_time_tuesday is None:
                    error['start_time_tuesday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_tuesday is None:
                    error['end_time_tuesday'] = ValidationError(validation_error, code='invalid')

            # Wednesday
            if value is True and key == 'wednesday':
                if self.start_time_wednesday is None:
                    error['start_time_wednesday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_wednesday is None:
                    error['end_time_wednesday'] = ValidationError(validation_error, code='invalid')

            # Thursday
            if value is True and key == 'thursday':
                if self.start_time_thursday is None:
                    error['start_time_thursday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_thursday is None:
                    error['end_time_thursday'] = ValidationError(validation_error, code='invalid')

            # Friday
            if value is True and key == 'friday':
                if self.start_time_friday is None:
                    error['start_time_friday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_friday is None:
                    error['end_time_friday'] = ValidationError(validation_error, code='invalid')

            # Saturday
            if value is True and key == 'saturday':
                if self.start_time_saturday is None:
                    error['start_time_saturday'] = ValidationError(validation_error, code='invalid')

                if self.end_time_saturday is None:
                    error['end_time_saturday'] = ValidationError(validation_error, code='invalid')

        if error:
            raise ValidationError(error)

    def profile(self):
        return Roster.objects.get(pk=self)

    @staticmethod
    def search_staff():
        return Roster.objects.filter(account__is_staff=True, account__is_superuser=False)

schedule/roster/forms.py
from django import forms
from django.contrib.auth import get_user_model

from roster import models


class FormProfile(forms.ModelForm):
    class Meta:
        model = get_user_model()

        fields = [
            'first_name',
            'last_name',
            'facility'
        ]


class FormSchedule(forms.ModelForm):
    class Meta:
        model = models.Roster

        fields = [
            'is_sunday',
            'has_break_sunday',
            'start_time_sunday',
            'end_time_sunday',
            'is_monday',
            'has_break_monday',
            'start_time_monday',
            'end_time_monday',
            'is_tuesday',
            'has_break_tuesday',
            'start_time_tuesday',
            'end_time_tuesday',
            'is_wednesday',
            'has_break_wednesday',
            'start_time_wednesday',
            'end_time_wednesday',
            'is_thursday',
            'has_break_thursday',
            'start_time_thursday',
            'end_time_thursday',
            'is_friday',
            'has_break_friday',
            'start_time_friday',
            'end_time_friday',
            'is_saturday',
            'has_break_saturday',
            'start_time_saturday',
            'end_time_saturday'
        ]

        widgets = {
            'start_time_sunday': forms.NumberInput,
            'end_time_sunday': forms.NumberInput,
            'start_time_monday': forms.NumberInput,
            'end_time_monday': forms.NumberInput,
            'start_time_tuesday': forms.NumberInput,
            'end_time_tuesday': forms.NumberInput,
            'start_time_wednesday': forms.NumberInput,
            'end_time_wednesday': forms.NumberInput,
            'start_time_thursday': forms.NumberInput,
            'end_time_thursday': forms.NumberInput,
            'start_time_friday': forms.NumberInput,
            'end_time_friday': forms.NumberInput,
            'start_time_saturday': forms.NumberInput,
            'end_time_saturday': forms.NumberInput
        }

schedule/roster/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views import generic

from roster import excel
from roster import forms
from roster import models


class Download(LoginRequiredMixin, generic.View):
    @staticmethod
    def get(request):
        return excel.generate_excel()


class PreviewAll(LoginRequiredMixin, generic.ListView):
    template_name = 'roster/preview_all.html'

    queryset = models.Roster.search_staff()

    ordering = 'account__last_name'


class PreviewEmployee(LoginRequiredMixin, generic.DetailView):
    template_name = 'roster/preview_employee.html'

    model = models.Roster


class Profile(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    form_class = forms.FormProfile

    template_name = 'roster/profile.html'

    success_message = _('Updated employee profile.')

    def get_object(self, queryset=None):
        return get_object_or_404(get_user_model(), pk=self.kwargs['pk'], is_staff=True)

    def get_success_url(self):
        return reverse_lazy('roster:profile', kwargs={'pk': self.kwargs['pk']})


class Schedule(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    form_class = forms.FormSchedule

    template_name = 'roster/schedule.html'

    model = models.Roster

    success_message = _('Updated employee schedule.')

    def get_success_url(self):
        return reverse_lazy('roster:schedule', kwargs={'pk': self.kwargs['pk']})


class Search(LoginRequiredMixin, generic.ListView):
    template_name = 'roster/search.html'

    queryset = get_user_model().objects.filter(is_staff=True, is_superuser=False)

    ordering = ('facility', 'last_name')

schedule/roster/templates/roster/edit.html
{% extends 'asset/layout/layout.html' %}

{% load compress %}

{% load static %}

{% block js %}
    {% compress js %}
        <script src="{% static 'roster/js/edit.js' %}"></script>
    {% endcompress %}
{% endblock %}

{% block content %}

    {% include 'roster/nav.html' with pk=object.pk %}

    <form action="{% url 'roster:edit' object.pk %}" method="post" novalidate>

        {% csrf_token %}

        <div class="card-deck mb-3">
            <div class="card">
                <div class="card-header">{{ _('Schedule') }}</div>

                <div class="card-body">
                    <div class="labelWrapper">
                        <div class="labelHeader">{{ _('Employee') }}</div>
                        <div>{{ object.account|escape }}</div>
                    </div>

                    <div class="labelWrapper">
                        <div class="labelHeader">{{ _('Facility') }}</div>
                        <div>{{ object.account.facility|escape|upper }}</div>
                    </div>

                    <div class="labelWrapper">
                        <div class="labelHeader">{{ _('Total Time') }}</div>
                        <div><span id="total_time"></span></div>
                    </div>

                    <div class="card-text bg-transparent border-0">
                        {% include 'form/submit_update.html' %}
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_sunday %}
                    {% include 'form/input.html' with input=form.start_time_sunday %}
                    {% include 'form/input.html' with input=form.end_time_sunday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_sunday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_sunday"></span></p>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_monday %}
                    {% include 'form/input.html' with input=form.start_time_monday %}
                    {% include 'form/input.html' with input=form.end_time_monday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_monday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_monday"></span></p>
                </div>
            </div>
        </div>

        <div class="card-deck mb-3">
            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_tuesday %}
                    {% include 'form/input.html' with input=form.start_time_tuesday %}
                    {% include 'form/input.html' with input=form.end_time_tuesday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_tuesday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_tuesday"></span></p>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_wednesday %}
                    {% include 'form/input.html' with input=form.start_time_wednesday %}
                    {% include 'form/input.html' with input=form.end_time_wednesday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_wednesday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_wednesday"></span></p>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_thursday %}
                    {% include 'form/input.html' with input=form.start_time_thursday %}
                    {% include 'form/input.html' with input=form.end_time_thursday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_thursday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_thursday"></span></p>
                </div>
            </div>
        </div>

        <div class="card-deck mb-3">
            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_friday %}
                    {% include 'form/input.html' with input=form.start_time_friday %}
                    {% include 'form/input.html' with input=form.end_time_friday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_friday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_friday"></span></p>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    {% include 'form/checkbox.html' with checkbox=form.is_saturday %}
                    {% include 'form/input.html' with input=form.start_time_saturday %}
                    {% include 'form/input.html' with input=form.end_time_saturday %}
                    {% include 'form/checkbox.html' with checkbox=form.has_break_saturday %}

                    <p class="card-text">{{ _('Hours') }}: <span id="total_saturday"></span></p>
                </div>
            </div>
        </div>

    </form>

{% endblock content %}

schedule/roster/templates/roster/nav.html
<ul class="nav nav-tabs mb-2">
    <li class="nav-item">
        <a href="{% url 'roster:search' %}"
           class="nav-link{% if request.resolver_match.url_name == 'search' %} active{% endif %} text-dark">
            <i class="fas fa-search"></i> {{ _('Search') }}</a>
    </li>

    {% if request.resolver_match.url_name == 'search' %}
        <li class="nav-item">
            <a href="{% url 'login:create' %}"
               class="nav-link{% if request.resolver_match.url_name == 'create' %} active{% endif %} text-dark">
                <i class="fas fa-plus-circle"></i> {{ _('Create') }}
            </a>
        </li>
    {% endif %}

    {% if request.resolver_match.url_name in 'search preview-all' %}
        <li class="nav-item">
            <a href="{% url 'roster:download' %}"
               class="nav-link text-dark">
                <i class="fas fa-download"></i> {{ _('Download') }}
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'roster:preview-all' %}"
               class="nav-link{% if request.resolver_match.url_name == 'preview-all' %} active{% endif %} text-dark">
                <i class="far fa-eye"></i> {{ _('Preview') }}
            </a>
        </li>
    {% endif %}

    {% if request.resolver_match.url_name in 'preview-employee profile schedule' %}
        <li class="nav-item">
            <a href="{% url 'roster:profile' pk %}"
               class="nav-link{% if request.resolver_match.url_name == 'profile' %} active{% endif %} text-dark">
                <i class="fas fa-user-tie"></i> {{ _('Profile') }}</a>
        </li>

        <li class="nav-item">
            <a href="{% url 'roster:schedule' pk %}"
               class="nav-link{% if request.resolver_match.url_name == 'schedule' %} active{% endif %} text-dark">
                <i class="far fa-calendar-alt"></i> {{ _('Schedule') }}
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'roster:preview-employee' pk %}"
               class="nav-link{% if request.resolver_match.url_name == 'preview-employee' %} active{% endif %} text-dark">
                <i class="far fa-eye"></i> {{ _('Preview') }}
            </a>
        </li>
    {% endif %}
</ul>

schedule/roster/templates/roster/profile.html
{% extends 'asset/layout/layout.html' %}

{% block content %}

    {% include 'roster/nav.html' with pk=object.pk %}

    <form action="{% url 'roster:profile' object.pk %}" method="post" novalidate>

        {% csrf_token %}

        <div class="row">
            <div class="col-lg-6 mb-3">
                <div class="card mb-3">
                    <div class="card-header">{{ _('Profile') }}</div>

                    <div class="card-body">
                        {% include 'form/input.html' with input=form.first_name is_required=True %}
                        {% include 'form/input.html' with input=form.last_name is_required=True %}
                        {% include 'form/select.html' with select=form.facility is_required=True %}
                    </div>

                    <div class="card-footer bg-transparent border-0">
                        {% include 'form/submit_update.html' %}
                    </div>
                </div>
            </div>
        </div>

    </form>

{% endblock content %}

schedule/roster/templates/roster/search.html
{% extends 'asset/layout/layout.html' %}

{% load form_dialog %}

{% load compress %}

{% load static %}

{% block js %}
    {% compress js %}
        <script src="{% static 'form/js/modal.js' %}"></script>
    {% endcompress %}
{% endblock %}

{% block content %}

    {% include 'roster/nav.html' %}

    <table class="table table-striped" id="search">
        <thead>
        <tr>
            <th scope="col" class="w-25">{{ _('Name') }}</th>

            <th scope="col" class="w-75">{{ _('Facility') }}</th>

            {% if perms.roster.view_schedule %}
                <th scope="col" class="text-center">{{ _('Schedule') }}</th>
            {% endif %}

            {% if perms.roster.view_roster %}
                <th scope="col" class="text-center">{{ _('Profile') }}</th>
            {% endif %}

            {% if perms.login.delete_account %}
                <th scope="col" class="text-center">{{ _('Delete') }}</th>
            {% endif %}
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item|escape }}</td>

                <td>{{ item.facility|escape|upper }}</td>

                {% if perms.roster.view_schedule %}
                    <td class="text-center">
                        <a href="{% url 'roster:schedule' item.pk %}" class="nounderline">
                            <button class="btn btn-success btn-xs"
                                    data-title="{{ _('Schedule') }}">

                                <i class="fas fa-calendar-alt" aria-hidden="true"></i>
                            </button>
                        </a>
                    </td>
                {% endif %}

                {% if perms.roster.view_roster %}
                    <td class="text-center">
                        <a href="{% url 'roster:profile' item.pk %}" class="nounderline">
                            <button class="btn btn-primary btn-xs"
                                    data-title="{{ _('Edit') }}">

                                <i class="fas fa-pencil-alt" aria-hidden="true"></i>
                            </button>
                        </a>
                    </td>
                {% endif %}

                {% if perms.login.delete_account %}
                    <td class="text-center">
                        <button class="btn btn-danger btn-xs btn-delete"
                                data-title="{{ _('Delete') }}"
                                data-url="{% url 'login:delete' item.pk %}"
                                id="{{ item.pk }}">

                            <i class="fas fa-trash-alt" aria-hidden="true"></i>
                        </button>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <form action="#" method="post" id="modal_url_delete">
        {% csrf_token %}

        {% gwhcp_form_dialog _('Continuing will remove this employee.') 'delete' %}
    </form>

{% endblock content %}